import "./globals.scss";
import { SessionProvider } from "@/components/provider/SessionProvider";

export const metadata = {
  title: "Hoon",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body>
        <SessionProvider>{children}</SessionProvider>
      </body>
    </html>
  );
}
