import "./globals.scss";
import ReactQueryProvider from "@/utils/ReactQueryProvider";
import { SessionProvider } from "@/utils/SessionProvider";

export const metadata = {
  title: "Hoon",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body>
        <ReactQueryProvider>
          <SessionProvider>{children}</SessionProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
